/*
 * file generated by gmock: I3Mock.hpp
 */
#ifndef I3MOCK_HPP
#define I3MOCK_HPP

#include <gmock/gmock.h>
#include "./given/I3I4.hpp"

namespace n1 {
namespace  {

class I3Mock : public I3
{
public:
    MOCK_METHOD0(f1, void());
};

} // namespace n1
} // namespace 

#endif // I3MOCK_HPP

