/*
 * file generated by gmock: TMock.hpp
 */
#ifndef TMOCK_HPP
#define TMOCK_HPP

#include <gmock/gmock.h>
#include "./given/T.hpp"

namespace n {

template<typename Elem>
class TMock : public T<Elem>
{
public:
    MOCK_CONST_METHOD0_T(GetSize, int());
    MOCK_METHOD1_T(Push, void(const Elem &));
};

} // namespace n

#endif // TMOCK_HPP

